mass = float(input("Enter the mass (in kilograms): "))
velocity = float(input("Enter the velocity (in m/s): "))
print("Enter the mass (in kilograms):", mass)
print("Enter the velocity (in m/s):", velocity)
kinetic_energy = (0.5*mass*velocity**2)
print("The kinetic energy is:", kinetic_energy)
